# Basic server properties
server:
  port: ${ADMIN_PORT:9001}

# Basic spring properties
spring:
  # Application
  application:
    name: ${AUDIT_APPLICATION_NAME:audit-service}

# Basic actuator properties
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:*}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_SHOW_DETAILS:always}